//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApEscritorio.ServicioWindows {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuarios", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ApEscritorio.ServicioWindows.Lector))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ApEscritorio.ServicioWindows.Administrador))]
    public partial class Usuarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NdocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomUsuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Ndoc {
            get {
                return this.NdocField;
            }
            set {
                if ((this.NdocField.Equals(value) != true)) {
                    this.NdocField = value;
                    this.RaisePropertyChanged("Ndoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomUsu {
            get {
                return this.NomUsuField;
            }
            set {
                if ((object.ReferenceEquals(this.NomUsuField, value) != true)) {
                    this.NomUsuField = value;
                    this.RaisePropertyChanged("NomUsu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lector", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Lector : ApEscritorio.ServicioWindows.Usuarios {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Administrador", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Administrador : ApEscritorio.ServicioWindows.Usuarios {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GeneraLectoresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GeneraLectores {
            get {
                return this.GeneraLectoresField;
            }
            set {
                if ((this.GeneraLectoresField.Equals(value) != true)) {
                    this.GeneraLectoresField = value;
                    this.RaisePropertyChanged("GeneraLectores");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Noticias", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Noticias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantComentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuerpoNoticiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHoraCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdNoticiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Queue<ApEscritorio.ServicioWindows.Comentarios> ListaComentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomPeriodistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApEscritorio.ServicioWindows.Periodista PeriodistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RelevanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResumenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantComentarios {
            get {
                return this.CantComentariosField;
            }
            set {
                if ((this.CantComentariosField.Equals(value) != true)) {
                    this.CantComentariosField = value;
                    this.RaisePropertyChanged("CantComentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuerpoNoticia {
            get {
                return this.CuerpoNoticiaField;
            }
            set {
                if ((object.ReferenceEquals(this.CuerpoNoticiaField, value) != true)) {
                    this.CuerpoNoticiaField = value;
                    this.RaisePropertyChanged("CuerpoNoticia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHoraCreacion {
            get {
                return this.FechaHoraCreacionField;
            }
            set {
                if ((this.FechaHoraCreacionField.Equals(value) != true)) {
                    this.FechaHoraCreacionField = value;
                    this.RaisePropertyChanged("FechaHoraCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNoticia {
            get {
                return this.IdNoticiaField;
            }
            set {
                if ((this.IdNoticiaField.Equals(value) != true)) {
                    this.IdNoticiaField = value;
                    this.RaisePropertyChanged("IdNoticia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Queue<ApEscritorio.ServicioWindows.Comentarios> ListaComentarios {
            get {
                return this.ListaComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaComentariosField, value) != true)) {
                    this.ListaComentariosField = value;
                    this.RaisePropertyChanged("ListaComentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPeriodista {
            get {
                return this.NomPeriodistaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomPeriodistaField, value) != true)) {
                    this.NomPeriodistaField = value;
                    this.RaisePropertyChanged("NomPeriodista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApEscritorio.ServicioWindows.Periodista Periodista {
            get {
                return this.PeriodistaField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodistaField, value) != true)) {
                    this.PeriodistaField = value;
                    this.RaisePropertyChanged("Periodista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Relevante {
            get {
                return this.RelevanteField;
            }
            set {
                if ((this.RelevanteField.Equals(value) != true)) {
                    this.RelevanteField = value;
                    this.RaisePropertyChanged("Relevante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resumen {
            get {
                return this.ResumenField;
            }
            set {
                if ((object.ReferenceEquals(this.ResumenField, value) != true)) {
                    this.ResumenField = value;
                    this.RaisePropertyChanged("Resumen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comentarios", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Comentarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdComentarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApEscritorio.ServicioWindows.Lector LectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comentario {
            get {
                return this.ComentarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentarioField, value) != true)) {
                    this.ComentarioField = value;
                    this.RaisePropertyChanged("Comentario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdComentario {
            get {
                return this.IdComentarioField;
            }
            set {
                if ((this.IdComentarioField.Equals(value) != true)) {
                    this.IdComentarioField = value;
                    this.RaisePropertyChanged("IdComentario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApEscritorio.ServicioWindows.Lector Lector {
            get {
                return this.LectorField;
            }
            set {
                if ((object.ReferenceEquals(this.LectorField, value) != true)) {
                    this.LectorField = value;
                    this.RaisePropertyChanged("Lector");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomUsuario {
            get {
                return this.NomUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NomUsuarioField, value) != true)) {
                    this.NomUsuarioField = value;
                    this.RaisePropertyChanged("NomUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Periodista", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Periodista : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechanacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ListaPremiosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NacionalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomPeriodistaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fechanacimiento {
            get {
                return this.FechanacimientoField;
            }
            set {
                if ((this.FechanacimientoField.Equals(value) != true)) {
                    this.FechanacimientoField = value;
                    this.RaisePropertyChanged("Fechanacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ListaPremios {
            get {
                return this.ListaPremiosField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaPremiosField, value) != true)) {
                    this.ListaPremiosField = value;
                    this.RaisePropertyChanged("ListaPremios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nacionalidad {
            get {
                return this.NacionalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.NacionalidadField, value) != true)) {
                    this.NacionalidadField = value;
                    this.RaisePropertyChanged("Nacionalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPeriodista {
            get {
                return this.NomPeriodistaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomPeriodistaField, value) != true)) {
                    this.NomPeriodistaField = value;
                    this.RaisePropertyChanged("NomPeriodista");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWindows.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AltaUsuario", ReplyAction="http://tempuri.org/IService1/AltaUsuarioResponse")]
        void AltaUsuario(ApEscritorio.ServicioWindows.Usuarios U, ApEscritorio.ServicioWindows.Administrador adminBD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogueoUsuario", ReplyAction="http://tempuri.org/IService1/LogueoUsuarioResponse")]
        ApEscritorio.ServicioWindows.Usuarios LogueoUsuario(string usuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BajaUsuario", ReplyAction="http://tempuri.org/IService1/BajaUsuarioResponse")]
        void BajaUsuario(ApEscritorio.ServicioWindows.Usuarios B);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarUsuario", ReplyAction="http://tempuri.org/IService1/ModificarUsuarioResponse")]
        void ModificarUsuario(ApEscritorio.ServicioWindows.Usuarios A);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarUsuario", ReplyAction="http://tempuri.org/IService1/BuscarUsuarioResponse")]
        ApEscritorio.ServicioWindows.Usuarios BuscarUsuario(long Ndoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarLector", ReplyAction="http://tempuri.org/IService1/ListarLectorResponse")]
        ApEscritorio.ServicioWindows.Lector[] ListarLector();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AltaNoticias", ReplyAction="http://tempuri.org/IService1/AltaNoticiasResponse")]
        void AltaNoticias(ApEscritorio.ServicioWindows.Noticias N, ApEscritorio.ServicioWindows.Administrador adminBD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BajaNoticia", ReplyAction="http://tempuri.org/IService1/BajaNoticiaResponse")]
        void BajaNoticia(ApEscritorio.ServicioWindows.Noticias N, ApEscritorio.ServicioWindows.Administrador adminBD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarNoticia", ReplyAction="http://tempuri.org/IService1/ModificarNoticiaResponse")]
        void ModificarNoticia(ApEscritorio.ServicioWindows.Noticias N, ApEscritorio.ServicioWindows.Administrador adminBD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarNoticia", ReplyAction="http://tempuri.org/IService1/BuscarNoticiaResponse")]
        ApEscritorio.ServicioWindows.Noticias BuscarNoticia(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarCompletoNoticias", ReplyAction="http://tempuri.org/IService1/ListarCompletoNoticiasResponse")]
        ApEscritorio.ServicioWindows.Noticias[] ListarCompletoNoticias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListoRelevantes", ReplyAction="http://tempuri.org/IService1/ListoRelevantesResponse")]
        ApEscritorio.ServicioWindows.Noticias[] ListoRelevantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListoEconomicas", ReplyAction="http://tempuri.org/IService1/ListoEconomicasResponse")]
        ApEscritorio.ServicioWindows.Noticias[] ListoEconomicas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListoPoliticas", ReplyAction="http://tempuri.org/IService1/ListoPoliticasResponse")]
        ApEscritorio.ServicioWindows.Noticias[] ListoPoliticas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListoPoliciales", ReplyAction="http://tempuri.org/IService1/ListoPolicialesResponse")]
        ApEscritorio.ServicioWindows.Noticias[] ListoPoliciales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListoInternacionales", ReplyAction="http://tempuri.org/IService1/ListoInternacionalesResponse")]
        ApEscritorio.ServicioWindows.Noticias[] ListoInternacionales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListadoNoticiasPeriodistaXML", ReplyAction="http://tempuri.org/IService1/ListadoNoticiasPeriodistaXMLResponse")]
        string ListadoNoticiasPeriodistaXML(ApEscritorio.ServicioWindows.Periodista P);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ComentarNoticia", ReplyAction="http://tempuri.org/IService1/ComentarNoticiaResponse")]
        void ComentarNoticia(ApEscritorio.ServicioWindows.Noticias N);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AltaPeriodista", ReplyAction="http://tempuri.org/IService1/AltaPeriodistaResponse")]
        void AltaPeriodista(ApEscritorio.ServicioWindows.Periodista L, ApEscritorio.ServicioWindows.Administrador adminBD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarPeriodista", ReplyAction="http://tempuri.org/IService1/BuscarPeriodistaResponse")]
        ApEscritorio.ServicioWindows.Periodista BuscarPeriodista(string l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarPeriodista", ReplyAction="http://tempuri.org/IService1/ListarPeriodistaResponse")]
        ApEscritorio.ServicioWindows.Periodista[] ListarPeriodista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BajaPeriodista", ReplyAction="http://tempuri.org/IService1/BajaPeriodistaResponse")]
        void BajaPeriodista(ApEscritorio.ServicioWindows.Periodista L, ApEscritorio.ServicioWindows.Administrador adminBD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModificarPeriodista", ReplyAction="http://tempuri.org/IService1/ModificarPeriodistaResponse")]
        void ModificarPeriodista(ApEscritorio.ServicioWindows.Periodista L, ApEscritorio.ServicioWindows.Administrador adminBD);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ApEscritorio.ServicioWindows.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ApEscritorio.ServicioWindows.IService1>, ApEscritorio.ServicioWindows.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AltaUsuario(ApEscritorio.ServicioWindows.Usuarios U, ApEscritorio.ServicioWindows.Administrador adminBD) {
            base.Channel.AltaUsuario(U, adminBD);
        }
        
        public ApEscritorio.ServicioWindows.Usuarios LogueoUsuario(string usuario, string contraseña) {
            return base.Channel.LogueoUsuario(usuario, contraseña);
        }
        
        public void BajaUsuario(ApEscritorio.ServicioWindows.Usuarios B) {
            base.Channel.BajaUsuario(B);
        }
        
        public void ModificarUsuario(ApEscritorio.ServicioWindows.Usuarios A) {
            base.Channel.ModificarUsuario(A);
        }
        
        public ApEscritorio.ServicioWindows.Usuarios BuscarUsuario(long Ndoc) {
            return base.Channel.BuscarUsuario(Ndoc);
        }
        
        public ApEscritorio.ServicioWindows.Lector[] ListarLector() {
            return base.Channel.ListarLector();
        }
        
        public void AltaNoticias(ApEscritorio.ServicioWindows.Noticias N, ApEscritorio.ServicioWindows.Administrador adminBD) {
            base.Channel.AltaNoticias(N, adminBD);
        }
        
        public void BajaNoticia(ApEscritorio.ServicioWindows.Noticias N, ApEscritorio.ServicioWindows.Administrador adminBD) {
            base.Channel.BajaNoticia(N, adminBD);
        }
        
        public void ModificarNoticia(ApEscritorio.ServicioWindows.Noticias N, ApEscritorio.ServicioWindows.Administrador adminBD) {
            base.Channel.ModificarNoticia(N, adminBD);
        }
        
        public ApEscritorio.ServicioWindows.Noticias BuscarNoticia(int n) {
            return base.Channel.BuscarNoticia(n);
        }
        
        public ApEscritorio.ServicioWindows.Noticias[] ListarCompletoNoticias() {
            return base.Channel.ListarCompletoNoticias();
        }
        
        public ApEscritorio.ServicioWindows.Noticias[] ListoRelevantes() {
            return base.Channel.ListoRelevantes();
        }
        
        public ApEscritorio.ServicioWindows.Noticias[] ListoEconomicas() {
            return base.Channel.ListoEconomicas();
        }
        
        public ApEscritorio.ServicioWindows.Noticias[] ListoPoliticas() {
            return base.Channel.ListoPoliticas();
        }
        
        public ApEscritorio.ServicioWindows.Noticias[] ListoPoliciales() {
            return base.Channel.ListoPoliciales();
        }
        
        public ApEscritorio.ServicioWindows.Noticias[] ListoInternacionales() {
            return base.Channel.ListoInternacionales();
        }
        
        public string ListadoNoticiasPeriodistaXML(ApEscritorio.ServicioWindows.Periodista P) {
            return base.Channel.ListadoNoticiasPeriodistaXML(P);
        }
        
        public void ComentarNoticia(ApEscritorio.ServicioWindows.Noticias N) {
            base.Channel.ComentarNoticia(N);
        }
        
        public void AltaPeriodista(ApEscritorio.ServicioWindows.Periodista L, ApEscritorio.ServicioWindows.Administrador adminBD) {
            base.Channel.AltaPeriodista(L, adminBD);
        }
        
        public ApEscritorio.ServicioWindows.Periodista BuscarPeriodista(string l) {
            return base.Channel.BuscarPeriodista(l);
        }
        
        public ApEscritorio.ServicioWindows.Periodista[] ListarPeriodista() {
            return base.Channel.ListarPeriodista();
        }
        
        public void BajaPeriodista(ApEscritorio.ServicioWindows.Periodista L, ApEscritorio.ServicioWindows.Administrador adminBD) {
            base.Channel.BajaPeriodista(L, adminBD);
        }
        
        public void ModificarPeriodista(ApEscritorio.ServicioWindows.Periodista L, ApEscritorio.ServicioWindows.Administrador adminBD) {
            base.Channel.ModificarPeriodista(L, adminBD);
        }
    }
}
